export const WITH_MD_CONVEX_FUNCTIONS = {
  queries: {
    reposList: 'repos:list',
    reposGet: 'repos:get',
    mdFilesListByRepo: 'mdFiles:listByRepo',
    mdFilesGet: 'mdFiles:get',
    mdFilesResolveByPath: 'mdFiles:resolveByPath',
    commentsListByFile: 'comments:listByFile',
    suggestionsListByFile: 'suggestions:listByFile',
    activitiesListByRepo: 'activities:listByRepo',
    pushQueueUnpushedCount: 'pushQueue:unpushedCount',
    pushQueueListByRepo: 'pushQueue:listByRepo',
    installationsGet: 'installations:get',
  },
  mutations: {
    commentsCreate: 'comments:create',
    commentsUpdate: 'comments:update',
    commentsResolve: 'comments:resolve',
    commentsDelete: 'comments:remove',
    mdFilesSaveSource: 'mdFiles:saveSource',
    mdFilesImportLocalBatch: 'mdFiles:importLocalBatch',
    mdFilesMovePath: 'mdFiles:movePath',
    mdFilesRenamePath: 'mdFiles:renamePath',
    mdFilesUndoFileOperation: 'mdFiles:undoFileOperation',
    mdFilesUpsertFromSync: 'mdFiles:upsertFromSync',
    mdFilesMarkMissingAsDeleted: 'mdFiles:markMissingAsDeleted',
    suggestionsCreate: 'suggestions:create',
    suggestionsAccept: 'suggestions:accept',
    suggestionsReject: 'suggestions:reject',
    reposResync: 'repos:resync',
    reposUpsertFromGithub: 'repos:upsertFromGithub',
    reposUpdateSyncStatus: 'repos:updateSyncStatus',
    reposEnsureSeedData: 'repos:ensureSeedData',
    reposRestoreFallbackFiles: 'repos:restoreFallbackFiles',
    pushQueuePushNow: 'pushQueue:pushNow',
    pushQueueMarkPushed: 'pushQueue:markPushed',
    activitiesMarkAsRead: 'activities:markAsRead',
    activitiesCreate: 'activities:create',
    usersUpsertFromGithub: 'users:upsertFromGithub',
    installationsUpsert: 'installations:upsert',
  },
} as const;
